In [1]:
import pandas as pd

path_folder = '../data/correspondence_tables/'
path_2018 = f'{path_folder}NST_2007_CN_2018.xlsx'
path_2019 = f'{path_folder}NST_2007_CN_2019.xlsx'
path_2020 = f'{path_folder}NST_2007_CN_2020.xlsx'
path_2021 = f'{path_folder}NST_2007_CN_2021.xlsx'

df_2018 = pd.read_excel(path_2018, dtype={'NST 2007': str, 'CN 2018': str}, usecols=['NST 2007', 'CN 2018'])
df_2019 = pd.read_excel(path_2019, dtype={'NST 2007': str, 'CN 2019': str}, usecols=['NST 2007', 'CN 2019'])
df_2020 = pd.read_excel(path_2020, dtype={'NST 2007': str, 'CN 2020': str}, usecols=['NST 2007', 'CN 2020'])
df_2021 = pd.read_excel(path_2021, dtype={'NST 2007': str, 'CN 2021': str}, usecols=['NST 2007', 'CN 2021'])
df_2018

c:\Users\ruide\OneDrive\P3Envs\geoFluxus\mowl\venv\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

     NST 2007     CN 2018
0        01.1  1001 11 00
1        01.1  1001 19 00
2        01.1  1001 91 10
3        01.1  1001 91 20
4        01.1  1001 91 90
...       ...         ...
9527     19.2  4906 00 00
9528     19.2  9701 10 00
9529     19.2  9701 90 00
9530     19.2  9702 00 00
9531     19.2  9703 00 00

[9532 rows x 2 columns]

In [2]:
path_en = '../data/NST_2007_EN.csv'
df_raw = pd.read_csv(path_en, dtype={'Code': str, 'Parent': str}, usecols=['Code', 'Parent', 'Description'])
df_raw = df_raw.dropna().rename(columns={'Code': 'NST 2007'})

df_raw

    NST 2007 Parent                                        Description
1       01.1     01                                            Cereals
2       01.2     01                                           Potatoes
3       01.3     01                                        Sugar beet
4       01.4     01                   Other fresh fruit and vegetables
5       01.5     01                   Products of forestry and logging
..       ...    ...                                                ...
93      17.5     17                      Other non market goods n.e.c.
95      18.0     18                                      Grouped goods
97      19.1     19  Unidentifiable goods in containers or swap bodies
98      19.2     19                         Other unidentifiable goods
100     20.0     20               Other goods not elsewhere classified

[81 rows x 3 columns]

In [3]:
checker = {}
checker_2 = {}

for i in range(df_raw.shape[0]):
  code = df_raw.iloc[i, 0]
  cn_codes = df_2018[df_2018['NST 2007'].isin([code])]
  #print(code, '--', cn_codes['CN 2018'].tolist())
  cn_raw = cn_codes['CN 2018'].tolist()
  checker[code] = sorted(cn_raw)

  #cn_proc = list(set([c.split(' ')[0] for c in cn_raw]))
  cn_proc = list(set([c[:-3] for c in cn_raw]))
  checker_2[code] = sorted(cn_proc)

In [4]:
with open('../data/temp/NST2007_CN2018.txt', 'w') as f:
  for k in checker.keys():
    f.write(f'{k} --> {checker[k]}\n')
    #print(k, '-->', checker[k])

In [5]:
with open('../data/temp/NST2007_CN2018_b.txt', 'w') as f:
  for k in checker_2.keys():
    f.write(f'{k} --> {checker_2[k]}\n')
    #print(k, '-->', checker[k])

#### Check if CN codes jumped NST in 2019

In [6]:
checker_2019 = {}

for i in range(df_raw.shape[0]):
  code = df_raw.iloc[i, 0]
  cn_codes = df_2019[df_2019['NST 2007'].isin([code])]
  #print(code, '--', cn_codes['CN 2019'].tolist())
  cn_raw = cn_codes['CN 2019'].tolist()
  checker_2019[code] = sorted(cn_raw)

In [7]:
for k,vals in checker_2019.items():
  for v in vals:
    temp = {key:v for key, val in checker.items() if (key != k and any(v in st for st in val))}
    if temp:
      # dictionary has content...
      for kc, vc in temp.items():
        print(f'{vc} is duplicate in {kc}')

#### Check if NST codes are specific to HS subheading aggregation (6 digits) --> they're not...

In [8]:
with open('../data/temp/HS_Checker.txt', 'w') as f:
  for k,vals in checker_2.items():
    for v in vals:
      temp = {key:v for key, val in checker_2.items() if (key != k and any(v in st for st in val))}
      if temp:
        # dictionary has content...
        for kc, vc in temp.items():
          #print(f'{vc} is duplicate in {kc}')
          f.write(f'{vc} is duplicate in {kc}\n')

#### Check if CN codes jumped NST in 2020

In [9]:
checker_2020 = {}

for i in range(df_raw.shape[0]):
  code = df_raw.iloc[i, 0]
  cn_codes = df_2020[df_2020['NST 2007'].isin([code])]
  #print(code, '--', cn_codes['CN 2020'].tolist())
  cn_raw = cn_codes['CN 2020'].tolist()
  checker_2020[code] = sorted(cn_raw)

In [10]:
for k,vals in checker_2020.items():
  for v in vals:
    temp = {key:v for key, val in checker_2019.items() if (key != k and any(v in st for st in val))}
    if temp:
      # dictionary has content...
      for kc, vc in temp.items():
        print(f'{vc} is duplicate in {kc}')

#### Check if CN codes jumped NST in 2021

In [11]:
checker_2021 = {}

for i in range(df_raw.shape[0]):
  code = df_raw.iloc[i, 0]
  cn_codes = df_2021[df_2021['NST 2007'].isin([code])]
  #print(code, '--', cn_codes['CN 2021'].tolist())
  cn_raw = cn_codes['CN 2021'].tolist()
  checker_2021[code] = sorted(cn_raw)

In [12]:
for k,vals in checker_2021.items():
  for v in vals:
    temp = {key:v for key, val in checker_2020.items() if (key != k and any(v in st for st in val))}
    if temp:
      # dictionary has content...
      for kc, vc in temp.items():
        print(f'{vc} is duplicate in {kc}')

#### Test filtering

In [13]:
testdict1 = {
  '12.c': ['001', '002', '004'],
  '13.c': ['003', '005'],
  '14.2': ['006', '007', '008']
}
testdict2 = {
  '12.c': ['001', '008', '004'],
  '13.c': ['003', '005'],
  '14.2': ['006', '007', '008']
}

for k,vals in testdict2.items():
  for v in vals:
    temp = {key:v for key, val in testdict1.items() if (key != k and any(v in st for st in val))}
    if temp:
      # dictionary has content...
      for kc, vc in temp.items():
        print(f'{vc} is duplicate in {kc}')

008 is duplicate in 14.2

In [14]:
diff_2019 = {}

for i in range(df_raw.shape[0]):
  code = df_raw.iloc[i, 0]
  cn_codes = df_2019[df_2019['NST 2007'].isin([code])]
  #print(code, '--', cn_codes['CN 2018'].tolist())
  #checker[code] = cn_codes['CN 2019'].tolist()
  cn_codes = cn_codes['CN 2019'].tolist()

  for cd in cn_codes:
    if not cd in checker[code]:
      print(code, '-->', cd, 'missing')

  #print(i, ' -->', cn_codes)
  #print(i, '*-->', checker[code])

04.2 --> 0308 30 80 missing
07.2 --> 2710 12 50 missing
10.2 --> 7606 12 11 missing
10.2 --> 7606 12 19 missing
11.8 --> 8443 13 32 missing
11.8 --> 8443 13 34 missing
11.8 --> 8443 13 38 missing

In [15]:
nst_codes = df_raw['NST 2007'].tolist()
print(len(nst_codes))
print(nst_codes)

81
['01.1', '01.2', '01.3', '01.4', '01.5', '01.6', '01.7', '01.8', '01.9', '01.A', '01.B', '02.1', '02.2', '02.3', '03.1', '03.2', '03.3', '03.4', '03.5', '03.6', '04.1', '04.2', '04.3', '04.4', '04.5', '04.6', '04.7', '04.8', '04.9', '05.1', '05.2', '05.3', '06.1', '06.2', '06.3', '07.1', '07.2', '07.3', '07.4', '08.1', '08.2', '08.3', '08.4', '08.5', '08.6', '08.7', '09.1', '09.2', '09.3', '10.1', '10.2', '10.3', '10.4', '10.5', '11.1', '11.2', '11.3', '11.4', '11.5', '11.6', '11.7', '11.8', '12.1', '12.2', '13.1', '13.2', '14.1', '14.2', '15.1', '15.2', '16.1', '16.2', '17.1', '17.2', '17.3', '17.4', '17.5', '18.0', '19.1', '19.2', '20.0']

### NST2007 - CE25 conversion

In [16]:
path_ce25 = f'{path_folder}CE25_NST2007.xlsx'

df_ce25 = pd.read_excel(path_ce25, sheet_name='Sheet1', converters={'CE25':str})
df_ce25

,CE25,CE25_Description,NST_Groups,Unnamed: 3
0,1,Land- en tuinbouwproducten,"01.1,01.2,01.3,01.4,01.6,01.7","01.1 Cereals, 01.2 Potatoes, 01.3 Sugar beet, ..."
1,2,Bosbouwproducten,01.5,01.5 Products of forestry and logging
2,3,"Veehouderij-, jacht- en visserijproducten","01.8,01.9,01.A,01.B","01.8 Live animals, 01.9 Raw milk from bovine c..."
3,4,"Voedsel, plantaardig","04.3,04.6","04.3 Fruits and vegetables, processed and pres..."
4,5,"Voedsel, dierlijk","04.1,04.2,04.5","04.1 Meat, raw hides, skins and meat products,..."
5,6,"Voedsel, overig","04.4,04.7,04.8,04.9","04.4 Animal and vegetable oils and fats, 04.7 ..."
6,7,"Steenkool, bruinkool, aardgas en ruwe aardolie","02.1,02.2,02.3","02.1 Coal and lignite, 02.2 Crude petroleum, ..."
7,8,Cokes en aardolieproducten,"07.1,07.2,07.3,07.4","07.1 Coke oven products, briquettes, ovoids an..."
8,9,Ertsen,"03.1,03.2,03.6","03.1 Iron ores, 03.2 Non-ferrous metal ores (e..."
9,10,"Zout, zand, grind, klei","03.3,03.4,03.5",03.3 Chemical and (natural) fertilizer mineral...
10,11,Overige minerale producten,"09.1,09.2,09.3","09.1 Glass and glass products, ceramic and por..."
11,12,Chemische producten en kunstmest,"08.1,08.3,08.2,08.7","08.1 Basic mineral chemical products, 08.3 Nit..."
12,13,Farmaceutica en chemische specialiteiten,08.5,08.5 Pharmaceuticals and parachemicals includi...
13,14,"Kunststoffen, rubber","08.4,08.6",08.4 Basic plastics and synthetic rubber in pr...
14,15,Basismetalen en basismetaalproducten,"10.1,10.2,10.3,10.4",10.1 Basic iron and steel and ferro-alloys and...
15,16,Metaalproducten,10.5,"10.5 Boilers, hardware, weapons and other fabr..."
16,17,Machines en apparaten voor de industrie,"11.1,11.8","11.1 Agricultural and forestry machinery, 11.8..."
17,18,Overige machines en apparaten,"11.2,11.3,11.4,11.5,11.6,11.7","11.2 Domestic appliances n.e.c. (white goods),..."
18,19,Transportmiddelen,"12.1,12.2","12.1 Automobile industry products, 12.2 Other ..."
19,20,Textiel,05.1,05.1 Textiles
20,21,"Kleding, bont en leer","05.2,05.3","05.2 Wearing apparel and articles of fur, 05.3..."
21,22,"Hout- en kurkproducten, papier en pulp","06.1,06.2",06.1 Products of wood and cork (except furnitu...
22,23,Meubels,13.1,13.1 Furniture
23,24,Afval,"14.1,14.2","14.1 Household and municipal waste, 14.2 Other..."
24,25,Overige goederen,"06.3,13.2,15.1,15.2,17.1,17.2,17.3,17.4,17.5,20.0","06.3 Printed matter and recorde media, 13.2 Ot..."

##### NST codes missing from CE 25 correspondence

In [17]:
for cd in nst_codes:
  if not df_ce25['NST_Groups'].str.contains(cd).any():
    print(f'NST {cd} has no correspondence in CE 25')

NST 16.1 has no correspondence in CE 25
NST 16.2 has no correspondence in CE 25
NST 18.0 has no correspondence in CE 25
NST 19.1 has no correspondence in CE 25
NST 19.2 has no correspondence in CE 25

#### Prepare dataframe for processing

In [18]:
df_ce25['NST_Groups'] = df_ce25['NST_Groups'].str.split(',')
#df_ce25['NST_Groups']

df_ce25['CE25'] = df_ce25['CE25'].str.zfill(2)
#df_ce25['CE25']

In [19]:
df_ce25

,CE25,CE25_Description,NST_Groups,Unnamed: 3
0,01,Land- en tuinbouwproducten,"[01.1, 01.2, 01.3, 01.4, 01.6, 01.7]","01.1 Cereals, 01.2 Potatoes, 01.3 Sugar beet, ..."
1,02,Bosbouwproducten,[01.5],01.5 Products of forestry and logging
2,03,"Veehouderij-, jacht- en visserijproducten","[01.8, 01.9, 01.A, 01.B]","01.8 Live animals, 01.9 Raw milk from bovine c..."
3,04,"Voedsel, plantaardig","[04.3, 04.6]","04.3 Fruits and vegetables, processed and pres..."
4,05,"Voedsel, dierlijk","[04.1, 04.2, 04.5]","04.1 Meat, raw hides, skins and meat products,..."
5,06,"Voedsel, overig","[04.4, 04.7, 04.8, 04.9]","04.4 Animal and vegetable oils and fats, 04.7 ..."
6,07,"Steenkool, bruinkool, aardgas en ruwe aardolie","[02.1, 02.2, 02.3]","02.1 Coal and lignite, 02.2 Crude petroleum, ..."
7,08,Cokes en aardolieproducten,"[07.1, 07.2, 07.3, 07.4]","07.1 Coke oven products, briquettes, ovoids an..."
8,09,Ertsen,"[03.1, 03.2, 03.6]","03.1 Iron ores, 03.2 Non-ferrous metal ores (e..."
9,10,"Zout, zand, grind, klei","[03.3, 03.4, 03.5]",03.3 Chemical and (natural) fertilizer mineral...
10,11,Overige minerale producten,"[09.1, 09.2, 09.3]","09.1 Glass and glass products, ceramic and por..."
11,12,Chemische producten en kunstmest,"[08.1, 08.3, 08.2, 08.7]","08.1 Basic mineral chemical products, 08.3 Nit..."
12,13,Farmaceutica en chemische specialiteiten,[08.5],08.5 Pharmaceuticals and parachemicals includi...
13,14,"Kunststoffen, rubber","[08.4, 08.6]",08.4 Basic plastics and synthetic rubber in pr...
14,15,Basismetalen en basismetaalproducten,"[10.1, 10.2, 10.3, 10.4]",10.1 Basic iron and steel and ferro-alloys and...
15,16,Metaalproducten,[10.5],"10.5 Boilers, hardware, weapons and other fabr..."
16,17,Machines en apparaten voor de industrie,"[11.1, 11.8]","11.1 Agricultural and forestry machinery, 11.8..."
17,18,Overige machines en apparaten,"[11.2, 11.3, 11.4, 11.5, 11.6, 11.7]","11.2 Domestic appliances n.e.c. (white goods),..."
18,19,Transportmiddelen,"[12.1, 12.2]","12.1 Automobile industry products, 12.2 Other ..."
19,20,Textiel,[05.1],05.1 Textiles
20,21,"Kleding, bont en leer","[05.2, 05.3]","05.2 Wearing apparel and articles of fur, 05.3..."
21,22,"Hout- en kurkproducten, papier en pulp","[06.1, 06.2]",06.1 Products of wood and cork (except furnitu...
22,23,Meubels,[13.1],13.1 Furniture
23,24,Afval,"[14.1, 14.2]","14.1 Household and municipal waste, 14.2 Other..."
24,25,Overige goederen,"[06.3, 13.2, 15.1, 15.2, 17.1, 17.2, 17.3, 17....","06.3 Printed matter and recorde media, 13.2 Ot..."

<font style="color: green">-- CE 25 Ontology --</font>

In [20]:
from owlready2 import *
import types

# create and populate ontology
onto_ce25 = get_ontology('http://www.semanticweb.org/geofluxus/ontologies/2022/CE25')
print(onto_ce25.base_iri)

http://www.semanticweb.org/geofluxus/ontologies/2022/CE25#

In [21]:
# onto_nst = get_ontology('../ontologies/nst2007.owl').load()
# print(onto_nst.base_iri)

# onto_ce25.imported_ontologies.append(onto_nst)

In [22]:
def assignNSTCode(name, code):
  name.NSTCode.append(code)

with onto_ce25:
  onto_ce25.metadata.versionInfo.append('1.1.0')
  onto_ce25.metadata.label.append('CE 25 Classification')
  onto_ce25.metadata.seeAlso.append('https://www.geofluxus.com/')
  class CE25(Thing):
    pass
    
  CE25.comment = [
    locstr(f'CE 25 Goederengroepen Circulaire Economie', lang='nl')
  ]
  CE25.label = [locstr('CE25 - Goederengroepen Circulaire Economie', lang='nl')]
  
  class NSTCode(DataProperty):
    range = [str]
  
  # class forNST(ObjectProperty):
  #   pass
  
  class CE25Code(DataProperty):
    range = [str]

  for index, row in df_ce25.iterrows():
    code_ce = str(row['CE25']).zfill(2)
    ce_desc = row['CE25_Description']
    nst_lst = row['NST_Groups']

    code = types.new_class(f'CE_{code_ce}', (CE25,))
    code.comment = [
      locstr(ce_desc, lang='nl'),
    ]
    code.label = [
      locstr(f'{code_ce} - {ce_desc}', lang='nl')
    ]
    code.CE25Code = [code_ce]

    for nst in nst_lst:
      # nst = 'NST_' + nst.replace('.','_')
      # print(onto_nst[nst].iri)
      assignNSTCode(code, nst)
      # code.forNST.append(onto_nst[nst])

In [23]:

close_world(CE25)
onto_ce25.save(file = '../ontologies/CE25.owl', format = "rdfxml")